$(document).ready(function(){
    var rome = {
        highlights: ["Pantheon", "Trevi Fountain", "Spanish Steps", "Piazza Navona"],
        highlights_about: ["The Pantheon is a former Roman temple, now a church, in Rome, Italy, on the site of an earlier temple commissioned by Marcus Agrippa during the reign of Augustus", "The Trevi Fountain is a fountain in the Trevi district in Rome, Italy, designed by Italian architect Nicola Salvi and completed by Pietro Bracci.It is the largest Baroque fountain in the city and one of the most famous fountains in the world. The fountain has appeared in several notable films, including Federico Fellini's La Dolce Vita and the eponymous Three Coins in the Fountain.", "The Spanish Steps are a set of steps in Rome, Italy, climbing a steep slope between the Piazza di Spagna at the base and Piazza Trinità dei Monti, dominated by the Trinità dei Monti church at the top.", "Piazza Navona is a piazza in Rome, Italy. It is built on the site of the Stadium of Domitian, built in the 1st century AD, and follows the form of the open space of the stadium."],
        highlights_images: ["https://en.parisinfo.com/var/otcp/sites/images/media/1.-photos/02.-sites-culturels-630-x-405/pantheon-vue-generale-630x405-c-thinkstock/36266-1-fre-FR/Pantheon-vue-generale-630x405-C-Thinkstock.jpg", "https://www.italyguides.it/images/gridfolio/rome/trevi/trevi.fountain.010.jpg", "http://i.huffpost.com/gen/3562948/images/o-SPANISH-STEPS-ROME-facebook.jpg", "http://www.reidsitaly.com/images/lazio/rome/sights/pz-navona1-long.jpg"],
        sights_activities: ["Colosseum", "Roman Forum", "Capitoline Museums","Chiesa di Santa Maria in Aracoeli"],
        sights_activities_about: ["The Roman Colosseum opened in 80 AD, and seats up to 50,000 people. It is deamed the most thrilling ancient sight in Rome. Centuries ago, gladiators fought in mortal combat and condemned prisoners fought wild beasts in this colosseum as a form of entertainment in front of large crowds. The colosseum fell to disrepair after the fall of the Roman Empire.","The Roman Forum was ancient Rome's showpiece centre, a grandiose distinct of marble-clad temples, basilicas and vibrant public spaces. Dating to the 7th century BC when it was first developed as an Etruscan burial ground, it fell into disrepair after the fall of the Roman Empire., Dating to 1471, the Capitoline Museums are te world's oldest national museums, house one of Italy's finest collections of classical sculpture. Crowd-pleaser include the iconic Lupa capitolina and the Galata morente, a moving depiction of a dying Gaul warrior. There's also a picuture gallery with masterpieces by Tintoretto, Rubens, Van Dyck and Caravaggio.","Atop the 14th-century Aracoeli staircase, this Romanesque gem is ome to srisp 15th-century frescoes by Pinturicchio and the santo bambino, a wooden baby Jesus believed to have healing powers, The original was pinched in 1994 but the copy apparently does the trick." ],
        sights_activities_images: ["https://upload.wikimedia.org/wikipedia/commons/5/53/Colosseum_in_Rome%2C_Italy_-_April_2007.jpg", "http://www.destination360.com/europe/italy/rome/images/s/roman-forum.jpg", "https://www.througheternity.com/upload/CONF83/20170201/capitoline_museums_tour-tSa-1479X424.jpg", "https://media-cdn.tripadvisor.com/media/photo-s/0a/21/9f/42/church-of-santa-maria.jpg"],
        shopping: ["La Rinascente", "Oviesse", "Cinecittadue Centro Commerciale"],
        shopping_about: ["Really good for ready-to-wear clothes for both men and women, househole linens, and sewing notions, ad have well-stocked perfume counters","A chain store that offers moderately price medium-quality clothes, and a variety of household goods.", "Shopping mall that offers around 100 stores with a wide range of merchandise."],
        shopping_images: ["https://www.rinascente.it/upl/cms/images/20130318/113801892_6109.jpg", "http://www.nuovasocieta.it/wp-content/uploads/2014/11/oviesse.jpg", "https://www.lapiadineria.com/up/Cinecittadue-680x365_c.jpg"],
        eating: ["Enoteca Provincia Romana","Casa Coppelle","Forno di Campo de' Fiori"],
        eating_about: ["Specialising in regional food and wine, this stylish wine bar-cum-restaurant offers a daily menu of pastas and mains, wine by the glass, finger foods and an evening aperitif. Service is friendly, and with an enviable location overlooking the Colonna di Traiano, it's top schoice. Lunchtime is busy but it quietens in the evening.","Exposed-brick walls, ooks, flowers and subdued lighting set the stage for wonderful French-inspired food at this intimate, romantic restaurant. There's a full range of starters and pastas but the real tour de force is the steak, which is cooked superbly and served with thinly sliced potato crisps.","This ever-buzzing bakery makes obscenely good pizza al taglio, as well as panini and savoury snacks. There are two branches on either side of Via dei Cappellari on Campo de' Fiori. Grab a slice or three of oizza bianca - pizza with olive oil, rosemary and salt - pair ot with an occhio di bue (apricot-jam tarlet) and munch to your heart's conent on the piazza outside."],
        eating_images: ["https://www.timeout.com/wp-content/uploads/2014/06/Enoteca-Roma-2_F-325x215.jpg", "http://www.casacoppelle.com/images/cc%20present%2011nov2015-31.jpg?crc=4284739922", "http://www.puntarellarossa.it/wp/wp-content/uploads/2014/10/antico-forno-roscioli-forno-roma.jpg"],
        entertainment: ["Auditorium Parco della Musica", "Nuovo Cinema Palazzo", "Caffè Letterario"],
        entertainment_about: ["Auditorium Parco della Musica is a large multi-functional public music complex in Rome, Italy. The complex is situated in the north of the city, in the area where the 1960 Summer Olympic Games were held.", "Students, artists and activists are breathing new life into San Lorenzo's former Palace Cinema with a bevy of exciting creative happenings: think film screenings, theatre performances, DJ sets, concerts, live music, break dance classes and a host of other artsy events. In warm weather, the action spills outside onto the street terrace, overlooked by a B&W stencil mural by Rome street artists Sten & Lex.", "Caffè Letterario is an intellectual hangout housed in the funky converted, post-industrial space of a former garage. It combines designer looks, a bookshop, gallery, co-working space, performance area and lounge bar. There are regular gigs from 10pm to midnight, ranging from soul and jazz to Indian dance."],
        entertainment_images: ["http://yeshotel.sr1.delphinet.it/files/2013/03/Auditorium_Parco_della_Musica_cavea_Rome.jpg", "http://www.omero.it/media/320/20130314-ex-cinema-palazzo-panoramica_full.jpg","https://res.cloudinary.com/wanderable/image/upload/v1449698434/pvf5xye5t8bop2i8xtud.jpg"],
    }
    
    console.log("hi")
    var pathname = window.location.search;
    var location = pathname.split("=")[1]

    
    
    var brussels = {
        highlights: ["Le Grand Place", "Belgian Brewers Museum", "Musee du Cacao et du Chocolat", "Ste-Catherine & St-Gery", "Cathedrale des Sts Michel & Gudule", "Centre Belge De la Bande Dessinee", "Musees Royaux des Beaux-Arts de Belgique", "Musee des Instruments de Musique"],
        highlights_about: ["Must see: Hotel de Ville, Maison des Boulangers, Le Cornet, Le Renard, Le Cygne, La Maison des Ducs de Brabant, and LeMaison du Roi.", "Beer in Belgium is a seriously fun business. While it's treated as earnestly as wine in France, it has a far more egalitarian purpose here, although with around 600 brews on offer, Belgian beer can seem as intimidating as a French wine list.", "Chocolates are a synonymous with Belgium as beer is - Belgians are master-craftsmen and connoisseurs of both, and most travellers leave Brussels airport laden with Westmalles and Wittamers, Leffes, and Leonidas. All Belgian chocolate is fine and Belgians would to the streets to protest anything less.", "The charming laid-back neighborhoods of Ste-Catherine and St-Gery may comprise Brussels' oldest quarters, yet today they are the most contemporary and cutting edge areas.", "This imposing, solemn twin-towered church, constructed over three centuries from 1226 is a splendid sight, especially with its atmospheric lighting at night. Originally a chapel dedicated to St-Michel, as early as the 9th century, it was replaced by a Romanesque church in the 11th century.", "Illustrated stories have been inspiring , humoring, and capturing the imaginations of Belgians anf foreign comic enthusiasts for nearly a century, and the Belgian Cnetre for Comic Strip Art, or Comic Strip Museum, is a wonderful showcase for Belgium's favorite art.", "Enjoying the exeptional collections of artworks of of the Royal Museums of Fine Arts of Belgium - stretched across several museums - is high on many visitor's list of things to do in Brussels.", "This magical musical instrument museum, also known as MIM, has has a brilliant collectionof over 1500 instruments housed in a classic Art Nouveau building."],
        highlights_images: ["http://www.10cose.it/wp-content/uploads/2016/02/grand-place-bruxelles-696x415.jpg", "http://independentbartampa.com/wp-content/uploads/2016/02/Screen-Shot-2016-02-29-at-1.32.36-PM.png", "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Photo_Fa%C3%A7ade.jpg/1200px-Photo_Fa%C3%A7ade.jpg", "https://static-red-teviotcreative1455281384.netdna-ssl.com/wp-content/uploads/2015/10/Brussels_Sight_SaintGery-5.jpg", "http://i1.trekearth.com/photos/87913/saint-michel_et_saint-gudule.jpg", "http://www.ousejourner.com/photos/etablissement-297.jpg", "https://res.cloudinary.com/dk/image/upload/c_fit,w_5000/c_crop,h_1895,w_5000,x_0,y_511/fl_keep_iptc,q_70,c_fill,h_452,w_1192,f_auto/brussels/musees-royaux-beaux-arts-belgique.jpg", "http://farm4.static.flickr.com/3420/5715904621_b8543ccec6.jpg"],
        sights_activities: ["Autoworld","BOZAR", "Bruxella 1238", "Fondation Jacques Brel", "Eglise Notre Dame de la Chapelle", "Foret de Soignes", "Parc Leopold"],
        sights_activities_about: ["This museum in Parc du Cinquantaire is strictly one for car buffs. It consists of three private collection: one of motor vehicles, one of two wheelers and a collection of coaches and carriages.", "This vibrant arts and cultural space, also known as the Palais des Beaux arts is a magnanimous host to myriad performing arts events, exciting exhibitions on art, photography, decorative arts and design.", "Municipal workers accidentally discovered these underground remains of a 13th century Franciscan convent beneath the Bourse in 1988.", "Initially rejected by the Belgians, Brussels-born jacques Breks shone in Paris - his moving lyrics about the working-class helped make him one of Europe's most successful singer-songwriters.", "A fascinating blend of Romanesque and Gothic styles, the city's oldest church was completed in the 13th century.", "The forest parks of Foret de Soignes in the southest of Brussels with their peaceful ponds provide lovely tranquil escapes from the city. The meditative 12th century monastary, Abbaye de la Cambre, and Rouge Cloitre, a 14th century abbey, make the setting very picturesque", "This hilly parkm behind the European Parliament has a small lake, but apart from local kids playing basketball and the odd person walking a dog, it's used more as a thoroughfare than a place to relax"],
        sights_activities_images: ["http://www.visionsoftravel.org/wp-content/uploads/2017/01/AutoWorld-auto-museum-Brussels-Belgium-025-3.jpg", "https://en.wikiarquitectura.com/wp-content/uploads/2017/01/Bozar_28729.gif", "http://www.musea.brussels/mobile/images/qr/bruxella.jpg", "http://modellist-id.com/wp-content/uploads/image/original/Brel%20Brussels.jpg", "https://upload.wikimedia.org/wikipedia/commons/4/41/Bruxelles-Notre-Dame-de-la-Chapelle.jpg", "https://res.cloudinary.com/dk/image/upload/q_80,c_fit,w_1200,h_630,f_auto/brussels/foret-des-soignes.jpg", "https://upload.wikimedia.org/wikipedia/commons/0/02/Parc_L%C3%A9opold-Bruxelles04.JPG"],
        shopping: ["Galerie Agora", "Rue Blanche", "Sablon Antiques Center", "Libraire des Galeries", "La Boite a Musique", "La Boutique Tintin"],
        shopping_about: ["This lievly arcade is worth a look for its hundre-plus shops. WHile some sell street wear, hippy gear and disco threads, most shops sell leather - jackets, coats, belts and bags. Although a ot of the stufff is dated in style, other pieces are classics, and some of the retro-looking jackets are just too cool.", "This is probably the closest thing that Rue Antoine Dansaert has to a high street store. This stylish shop (with arty window displays) established by Belgian designers, specialises in colorful, fun, classic pieces that easily mix and match, and coordinate with their vibrant accessories.", "There are scores of antique stores on the PLace du Grand Sablon and its surrounding streets, but here you have a couple of dozen dealers in a 'one-stop-shop' on the Sablon itself, selling everything from ceramics and jewellry to furniture and fine art.", "This wonderful bookshop in the elegant Galerie du Rois has some coffee table books on Belgium, rich in history, art and architecture, as ewll as travel guides, along with fabulous books on fine arts, performing arts, and artists in general.", "With a comprehensive classical-music and opera CD and DVD collection that many consider to be the best in Europe, it's impossible to leave here without finding what you want.", "Tourists cram this store to take home the much-coveted comic books about traveller-reporter Tintin's global adventures that seem to be igniting imaginations increasingly more these days."],
        shopping_images: ["https://s3-media2.fl.yelpcdn.com/bphoto/4Byd1kbt4y12iiC8BLvoog/168s.jpg", "https://cdn-01.cityplug.be/library/1600x1200/place/3UNWND8F/RCYO8T51.jpg", "https://i1.wp.com/www.fleamarketinsiders.com/wp-content/uploads/2013/10/Brussels-flea-market.jpg?w=669&h=502&crop&ssl=1", "http://www.ebru.be/Architectuur/pics/arch1000tropismes01.jpg", "https://i2.wp.com/gramilano.com/wp-content/uploads/2012/10/P9220335-400x300.jpg?resize=400%2C300", "https://c2.staticflickr.com/4/3234/2952430878_8454e551f6_z.jpg?zz=1"],
        eating: ["A M Sweet", "L'Ane Vert", "Aux Armes de Bruxelles", "Waka Moon", "Eat and Love", "Mano & Mano", "Rouge Tomate", "Brasserie Ploegmans", "Le Fourneau", "Kasbah"],
        eating_about: ["This delightful sweet shop sells Belgian chocolates, biscuts and confectionary in charming packaging, and Freres Mariage teas from Paris, as well as home-baked cakes, pies and pastries.", "This welcoming local brasserie serves up hearty dishes such as coq au vin (chicken stew) in its cozy room, and outside when the weather is agreeable. There are some decent vegitarian options on the menu and some good wines and beers are offered as well.", "In a street where dining is a minefield of mussel places, this elegant eatery is where locals come to get treated royally and et some fantastic seafood. The oysters are the freshest around and for mains try any version of the mussels or fish.", "This funky corner cafe inn a converted bookshop serves up African cooking to locals who congregate at the outside tables when the weather permits. There is plenty of chicken on the menu and the eclectic interior's zebra-stripped chairs are snapchat worthy.", "We've long since stopped questions why Brussels has sucha a plethora of restaurants with both Vietnamese and Thai sharing the same menu, but we've given this stylish little place the benefit of the doubt because it does both so well.", "On Rue St-Boniface, Brussels newest 'eat-street', this simple Italian restaurant headed up by two Sicilian chefs does great business by serving up good-value fresh pastas, salads, and tasty pizzas late into the night.", "Rouge Tomate has a rosy glow tht's as fresh as the food they offer. Start off with a light dish such as the marinated scallops and move on to one of the excellent fish or pasta mains. there are small vineyard wines offered and outdoor seating when the weather cooperates.", "This authentic working-class bar is a classic, filled with crusty regulars who bemoan the fact that the food's gone ass trendy. However, while the white plates and presentation add an air of sophistication, thankfully the food here remains rustic.", "With a layout that echos Paris' L'Atelier de Joel Robuchon where diners perch on bar stools around an open kitchen, Le Fourneau does brisk business serving up tasting-sized servings of seafood and meat. After sampling the cute portions of fresh seafood, you can move on to main courses or just keep grazing the menu", "The favorite Middle East eatery of the fashion district in downtown Brussels, the Kasbah does a decent approximation of Middle East favorites such as tasty mezze and steaming couscous while sipping Moroccan wine."],
        eating_images: ["http://www.samenopcafe.be/on%20line%20foto%27s%20maxi/Brussel%20Brussel%20AM%20Sweet%201.JPG", "https://u.tfstatic.com/restaurant_photos/993/55993/169/612/l-ane-vert-vue-salle-14336.jpg", "https://traveltoeat.com/wp-content/uploads/2013/07/wpid-Photo-Jul-10-2013-533-AM.jpg", "http://www.arthurwyatt.co.uk/images/photos/brussels/s_brussels05.jpg", "https://s-media-cache-ak0.pinimg.com/736x/9b/e3/2f/9be32fa58a738bde2045c315be6d216b--flandre-ma-belle.jpg", "https://media-cdn.tripadvisor.com/media/photo-s/02/65/67/d5/filename-js-4874-jpg.jpg", "https://static1.squarespace.com/static/5786046d5016e1bd4868f0fa/58175bf9f7e0ab86f3d1b503/581f2629e58c62bd0982ec8b/1478437114324/background2.jpg", "https://media-cdn.tripadvisor.com/media/photo-o/05/d3/26/c5/lr6-brasserie-concert.jpg", "http://bienmangerabruxelles.blogs.lalibre.be/media/01/00/363027614.jpg", "https://cdn-01.cityplug.be/library/1600x1200/place/EWLD3E6K/YDLM28ND.jpg"],
        entertainment: ["Cafe Central"],
        entertainment_about: ["While the decor or this dark bar is traditional - very cozy on a winter's night - its avant garde attitude makes it anything but!"],
        entertainment_images: ["https://media02.cdn.agenda.be/d10acc18f8cda448ccf16d287fe6368bd8a2c03b.jpg?wl=500"],
    }
    var current_city;
    if (location == "brussels" || location == "Brussels"){
        current_city = brussels
    }
    else if (location == "rome" || location == "Rome"){
        current_city = rome
    }
    
    
    
    
    $("body").append("<div class='banner'><h2 style=center>Highlights</h2></div>")
    $("body").append("<div class= 'row'>")
    for(var i = 0; i<current_city.highlights.length;i++)
        $("body").append("<div class='card'><img class='card-img-top' src='" + current_city.highlights_images[i] + "' alt='Card image cap'><div class='card-block'><h4 class='card-title banner'>'"+ current_city.highlights[i] +"'</h4><p class='card-text'>'"+ current_city.highlights_about[i] + "'</p></div></div>")
    $("body").append("</div>")
    $("body").append("<div class='banner'><h2>Sights and Activities</h2></div>")
    for(var i = 0; i<current_city.sights_activities.length;i++)
    $("body").append("<div class='card'><img class='card-img-top' src='" + current_city.sights_activities_images[i] +"' alt='Card image cap'><div class='card-block'><h4 class='card-title banner'>'"+ current_city.sights_activities[i] +"'</h4><p class='card-text'>'"+ current_city.sights_activities_about[i] + "'</p></div></div>")
    $("body").append("<div class='banner'><h2>Shopping</h2></div>")
    for(var i = 0; i<current_city.shopping.length;i++)
    $("body").append("<div class='card'><img class='card-img-top' src='" + current_city.shopping_images[i] +"' alt='Card image cap'><div class='card-block'><h4 class='card-title banner'>'"+ current_city.shopping[i] +"'</h4><p class='card-text'>'"+ current_city.shopping_about[i] + "'</p></div></div>")
    $("body").append("<div class='banner><h2>Restaurants and Cafes</h2></div>")
    for(var i = 0; i<current_city.eating.length;i++)
    $("body").append("<div class='card'><img class='card-img-top' src='" + current_city.eating_images[i] +"' alt='Card image cap'><div class='card-block'><h4 class='card-title banner'>'"+ current_city.eating[i] +"'</h4><p class='card-text'>'"+ current_city.eating_about[i] + "'</p></div></div>")
    $("body").append("<div class='banner'><h2>Entertainment</h2></div>")
    for(var i = 0; i<current_city.entertainment.length;i++)
    $("body").append("<div class='card'><img class='card-img-top' src='" + current_city.entertainment_images[i] +"' alt='Card image cap'><div class='card-block'><h4 class='card-title banner'>'"+ current_city.entertainment[i] +"'</h4><p class='card-text'>'"+ current_city.entertainment_about[i] + "'</p></div></div>")
})